#!/usr/bin/env python3
"""
build_db.py - Convert Flipper Zero IRDB to C++ PROGMEM database.

Usage:
  python3 scripts/build_db.py /path/to/Flipper-IRDB-main

Outputs:
  src/DeviceDatabase.cpp (auto-generated, do not edit by hand)
"""
import sys
import os
import re

def sanitize_id(name):
    """Convert a string to a valid C++ identifier."""
    s = re.sub(r'[^a-zA-Z0-9]', '_', name)
    s = re.sub(r'_+', '_', s).strip('_')
    if s and s[0].isdigit():
        s = '_' + s
    return s

def parse_flipper_hex(hex_str):
    """Flipper stores LE byte strings: '04 00 00 00' -> '0x04'."""
    parts = hex_str.strip().split()
    if not parts:
        return "0x00"
    parts.reverse()
    hex_val = "".join(parts).lstrip('0')
    if not hex_val:
        hex_val = "0"
    return f"0x{hex_val.upper()}"

def parse_ir_file(filepath):
    """Parse a .ir file, return (protocol, address, [(cmd_name, hex_code)])."""
    protocol = None
    address = None
    commands = []
    current_name = ""
    current_type = ""

    try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#') or line.startswith('Filetype:') or line.startswith('Version:'):
                    continue
                if line.startswith('name:'):
                    current_name = line.split(':', 1)[1].strip()
                elif line.startswith('type:'):
                    current_type = line.split(':', 1)[1].strip()
                elif line.startswith('protocol:'):
                    protocol = line.split(':', 1)[1].strip()
                elif line.startswith('address:'):
                    address = parse_flipper_hex(line.split(':', 1)[1].strip())
                elif line.startswith('command:'):
                    if current_type == "parsed" and current_name:
                        hex_cmd = parse_flipper_hex(line.split(':', 1)[1].strip())
                        commands.append((current_name, hex_cmd))
                    current_name = ""
    except Exception:
        return None

    if not commands or not protocol:
        return None
    if not address:
        address = "0x00"
    return (protocol, address, commands)

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 scripts/build_db.py /path/to/Flipper-IRDB-main", file=sys.stderr)
        sys.exit(1)

    irdb_root = sys.argv[1]
    if not os.path.isdir(irdb_root):
        print(f"Error: {irdb_root} is not a directory", file=sys.stderr)
        sys.exit(1)

    # Scan all top-level directories as categories
    categories = {}
    skip_dirs = {'.git', '_Converted_', '__pycache__'}
    
    for cat_name in sorted(os.listdir(irdb_root)):
        cat_path = os.path.join(irdb_root, cat_name)
        if not os.path.isdir(cat_path) or cat_name.startswith('.') or cat_name in skip_dirs:
            continue
        
        profiles = []
        # Walk all .ir files under this category
        for root, dirs, files in os.walk(cat_path):
            for fname in sorted(files):
                if not fname.endswith('.ir'):
                    continue
                fpath = os.path.join(root, fname)
                result = parse_ir_file(fpath)
                if result is None:
                    continue
                protocol, address, commands = result
                
                # Build a human-readable brand name from the parent dir + filename
                rel = os.path.relpath(fpath, cat_path)
                brand_parts = os.path.dirname(rel)
                file_stem = fname.replace('.ir', '')
                if brand_parts:
                    brand = f"{brand_parts}/{file_stem}"
                else:
                    brand = file_stem
                
                profiles.append({
                    'brand': brand,
                    'protocol': protocol,
                    'address': address,
                    'commands': commands,
                })
        
        if profiles:
            categories[cat_name] = profiles

    # Generate C++ output
    out_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'src', 'DeviceDatabase.cpp')
    
    total_profiles = sum(len(p) for p in categories.values())
    print(f"Generating {out_path}", file=sys.stderr)
    print(f"  Categories: {len(categories)}", file=sys.stderr)
    print(f"  Total profiles: {total_profiles}", file=sys.stderr)

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write("// ============================================================\n")
        f.write("// AUTO-GENERATED by scripts/build_db.py — DO NOT EDIT BY HAND\n")
        f.write("// ============================================================\n")
        f.write('#include "DeviceDatabase.h"\n\n')

        # Emit command arrays and profile arrays per category
        for cat_name, profiles in categories.items():
            cat_id = sanitize_id(cat_name)
            f.write(f"// ---- Category: {cat_name} ({len(profiles)} profiles) ----\n\n")

            # Per-profile command arrays
            for pi, prof in enumerate(profiles):
                cmd_id = f"cmds_{cat_id}_{pi}"
                f.write(f"static const DeviceCommandStatic {cmd_id}[] = {{\n")
                for ci, (cname, chex) in enumerate(prof['commands']):
                    # Escape quotes in command names
                    cname_escaped = cname.replace('"', '\\"')
                    comma = "," if ci < len(prof['commands']) - 1 else ""
                    f.write(f'  {{"{cname_escaped}", "{chex}"}}{comma}\n')
                f.write(f"}};\n\n")

            # Profile array for this category
            f.write(f"static const DeviceProfileStatic profiles_{cat_id}[] = {{\n")
            for pi, prof in enumerate(profiles):
                cmd_id = f"cmds_{cat_id}_{pi}"
                brand_escaped = prof['brand'].replace('"', '\\"')
                comma = "," if pi < len(profiles) - 1 else ""
                f.write(f'  {{"{brand_escaped}", "{prof["protocol"]}", "{prof["address"]}", {cmd_id}, {len(prof["commands"])}}}{comma}\n')
            f.write(f"}};\n\n")

        # Emit the top-level categories array
        f.write("// ---- All Categories ----\n\n")
        f.write(f"static const DeviceCategoryStatic ALL_CATEGORIES[] = {{\n")
        for ci, (cat_name, profiles) in enumerate(categories.items()):
            cat_id = sanitize_id(cat_name)
            comma = "," if ci < len(categories) - 1 else ""
            f.write(f'  {{"{cat_name}", profiles_{cat_id}, {len(profiles)}}}{comma}\n')
        f.write(f"}};\n\n")
        f.write(f"static constexpr size_t ALL_CATEGORIES_COUNT = {len(categories)};\n\n")

        # Emit accessor functions
        f.write("// ---- Accessor Functions ----\n\n")
        f.write("size_t DeviceDatabase::getCategoryCount() {\n")
        f.write("  return ALL_CATEGORIES_COUNT;\n")
        f.write("}\n\n")
        
        f.write("const char* DeviceDatabase::getCategoryName(size_t categoryIndex) {\n")
        f.write("  if (categoryIndex >= ALL_CATEGORIES_COUNT) return \"\";\n")
        f.write("  return ALL_CATEGORIES[categoryIndex].name;\n")
        f.write("}\n\n")
        
        f.write("size_t DeviceDatabase::getProfileCount(size_t categoryIndex) {\n")
        f.write("  if (categoryIndex >= ALL_CATEGORIES_COUNT) return 0;\n")
        f.write("  return ALL_CATEGORIES[categoryIndex].profileCount;\n")
        f.write("}\n\n")
        
        f.write("const DeviceProfileStatic* DeviceDatabase::getProfile(size_t categoryIndex, size_t profileIndex) {\n")
        f.write("  if (categoryIndex >= ALL_CATEGORIES_COUNT) return nullptr;\n")
        f.write("  const auto& cat = ALL_CATEGORIES[categoryIndex];\n")
        f.write("  if (profileIndex >= cat.profileCount) return nullptr;\n")
        f.write("  return &cat.profiles[profileIndex];\n")
        f.write("}\n\n")
        
        f.write("DeviceProfile DeviceDatabase::toDynamic(const DeviceProfileStatic* profile) {\n")
        f.write("  DeviceProfile dp;\n")
        f.write("  if (!profile) return dp;\n")
        f.write("  dp.brand = profile->brand;\n")
        f.write("  dp.protocol = profile->protocol;\n")
        f.write("  dp.address = profile->address;\n")
        f.write("  for (size_t i = 0; i < profile->commandCount; i++) {\n")
        f.write("    dp.commands.push_back({profile->commands[i].name, profile->commands[i].hexCode});\n")
        f.write("  }\n")
        f.write("  return dp;\n")
        f.write("}\n")
    
    print(f"Done! Written to {out_path}", file=sys.stderr)

if __name__ == "__main__":
    main()
